Finsh register page and part of club detail page
cryptape/club-check-in pull request #3
Opened 2018-11-08 16:39 UTC by wangwenyue

Finsh register page.

Add link button for page switch.

Finsh club member page UI.

Add join club Modal in personal page.

2018-11-08 17:34 UTC, Keith-CY requested changes

2018-11-08 17:34 UTC, Keith-CY commented on src/components/Header/index.js
> +        const titleName = this.props.titleName
use `deconstruct` as `const { titleName } = this.props`

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Detail/ClubMember/index.js
> +                <Item
component items in an array should be labelled with `key`

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Detail/detail.css
> +    font-family: PingFangSC, Arial, sans-serif, serif;
repeated properties could be replaced with css variables.

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Detail/index.js
> +import {
imports from node_modules should be placed together

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Detail/detail.css
> +.club-detail-pannel {
`pannel` or `panel`, don't use both of them

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Detail/index.js
> +                <div className='club-detail-pannel'>
`pannel` or `panel`, don't use both of them

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Personal/ClubListItem/index.js
>                  <Flex onClick={handleClubDetail} className='club-list-item'>
add `key` to items in an array

2018-11-08 17:34 UTC, Keith-CY commented on src/containers/Personal/PersonalPanel/index.js
> +import {Link} from "react-router-dom"
space around `Link`

2018-11-08 17:34 UTC, Keith-CY commented on src/stores/personalStore/index.js
>  import React from "react";
semicolon could be removed

2018-11-08 17:34 UTC, Keith-CY commented on src/stores/personalStore/index.js
> +const prompt = Modal.prompt
use `deconstruct` as `const { prompt } = Modal`

2018-11-09 02:56 UTC, wangwenyue commented
@Keith-CY All requests resolved.

2018-11-09 02:59 UTC, Keith-CY approved these changes

2018-11-09 02:59 UTC, merged