Finish club detail page
cryptape/club-check-in pull request #5
Opened 2018-11-12 16:49 UTC by wangwenyue

Finish add money page.

Finish create club page.

Finish club detail page.

Add Modal for club detail page, add money page and create club page.

Write deploy instruction in README.md.

2018-11-12 17:24 UTC, Keith-CY requested changes

2018-11-12 17:24 UTC, Keith-CY commented on README.md
> +0.Install all dependency
dependency => dependencies

2018-11-12 17:24 UTC, Keith-CY commented on README.md
> +1.Use webpack generate production version
Use webpack `to` generate

2018-11-12 17:24 UTC, Keith-CY commented on src/containers/Manage/ManageClubDetail/index.js
> +                <span className='manageClubDetail__content--id'>ID:1001</span>
Normally we add space after `:`

2018-11-12 17:24 UTC, Keith-CY commented on src/containers/Manage/index.js
> +              placeholder="金额"
single quote

2018-11-12 17:24 UTC, Keith-CY commented on src/containers/New/index.js
> +          placeholder="写了你就别后悔"
single quote

2018-11-12 17:24 UTC, Keith-CY commented on src/containers/New/index.js
> +          placeholder="看你心情咯"
single quote

2018-11-13 01:22 UTC, wangwenyue commented
@Keith-CY all request resolved.

2018-11-13 02:14 UTC, Keith-CY approved these changes

2018-11-13 02:14 UTC, merged